// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Link: typeof import('./components/Link.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./components/tabs/TabBar.vue')['default']
    TabNav: typeof import('./components/tabs/TabNav.vue')['default']
    TabPane: typeof import('./components/tabs/TabPane.vue')['default']
    Tabs: typeof import('./components/tabs/Tabs.vue')['default']
  }
}

export {}
